# Generated by Django 4.2.1 on 2024-09-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="tags",
            field=models.ManyToManyField(blank=True, to="main.tags"),
        ),
    ]
