# Generated by Django 4.2.1 on 2024-09-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_posts_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="main.tags"
            ),
        ),
    ]
