# Generated by Django 4.2.1 on 2024-09-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_posts_cats"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("message", models.TextField()),
                ("time_create", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
