# Generated by Django 4.2.1 on 2024-10-10 21:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0009_comments_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categories",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="comments",
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
        migrations.AlterModelOptions(
            name="posts",
            options={"verbose_name": "Пост", "verbose_name_plural": "Посты"},
        ),
        migrations.AlterModelOptions(
            name="tags",
            options={"verbose_name": "Тег", "verbose_name_plural": "Теги"},
        ),
        migrations.AddField(
            model_name="posts",
            name="author",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auth",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="categories",
            name="cat_name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название категории"
            ),
        ),
        migrations.AlterField(
            model_name="comments",
            name="author_name",
            field=models.CharField(max_length=255, verbose_name="Автор"),
        ),
        migrations.AlterField(
            model_name="comments",
            name="message",
            field=models.TextField(verbose_name="Текст"),
        ),
        migrations.AlterField(
            model_name="comments",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="main.posts",
                verbose_name="Пост",
            ),
        ),
        migrations.AlterField(
            model_name="comments",
            name="time_create",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время создания"
            ),
        ),
        migrations.AlterField(
            model_name="posts",
            name="cats",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cats",
                to="main.categories",
                verbose_name="Категории",
            ),
        ),
        migrations.AlterField(
            model_name="posts",
            name="content",
            field=models.TextField(blank=True, verbose_name="Содержание"),
        ),
        migrations.AlterField(
            model_name="posts",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="main.tags", verbose_name="Теги"
            ),
        ),
        migrations.AlterField(
            model_name="posts",
            name="time_create",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время создания"
            ),
        ),
        migrations.AlterField(
            model_name="posts",
            name="title",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(3)],
                verbose_name="Заголовок",
            ),
        ),
        migrations.AlterField(
            model_name="posts",
            name="title_photo",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="photos/%Y/%m/%d/",
                verbose_name="Главное фото",
            ),
        ),
        migrations.AlterField(
            model_name="tags",
            name="tag_name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Назвение тега"
            ),
        ),
    ]
