# Generated by Django 4.2.1 on 2024-10-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_alter_comments_email_alter_comments_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
