name: First action integration test
run-name: ${{ github.actor }} is testing
on: [push]
jobs:
  test_forum:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
      - name: setup Python
        uses: actions/setup-python@v5

				