name: First action integration test
run-name: ${{ github.actor }} is testing
on:
  push:
   branches:
     - master
  pull_request:
   branches:
     - master	  
jobs:
  test_forum:
    runs-on: ubuntu-latest
    steps:
      - name: load repo
        uses: actions/checkout@v4
        with:
         repository: ${{ github.repository }}
      - name: setup Python
        id: python
        uses: actions/setup-python@v5
        with:
         python-version: "3.12"
      - name: install dependencies
        run: |
         python3 -m pip install --upgrade pip
         pip install -r requirements.txt
      - name: test forum
        run: |
         python3 manage.py test				