name: First action integration test
run-name: ${{ github.actor }} is testing
on:
  push:
   branches:
     - master
jobs:
  test_forum:
    runs-on: ubuntu-latest
    steps:
      - name: downoland repo
        uses: actions/checkout@v4
        with:
         repository: ${{ github.repository }}
      - name: setup Python
        id: python
        uses: actions/setup-python@v5
        with:
         python-version: "3.12"